### ISSUE TITLE
There are no data files in routing-server

### ISSUE THREAD

**Issue by remmas** [Leot6/AMoD#1]
hello,sorry to bother.I am  a new learner,when running the main program, the routing-server step will fail......can you upload these pickle files? or did i do something wrong?

  File "G:\phdU\ride-sharing\shixian\A unified approach to route planning for shared mobility\AMoD-master\lib\routing\routing_server.py", line 26, in <module>
    with open(f'{root_path}/data/path-tables-gitignore/NYC_SPT_{TRAVEL_TIME}_{str(i)}.pickle', 'rb') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'G:\\phdU\\ride-sharing\\shixian\\A unified approach to route planning for shared mobility\\AMoD-master/data/path-tables-gitignore/NYC_SPT_WEEK_0.pickle'

**Comment by Leot6** [comment]
Sorry for replying so late, I haven't checked my github website in quite some time.
Those missing data files could be generated using another repository: Manhattan-Map (https://github.com/Leot6/Manhattan-Map). Besides, I have updated them to OneDrive and Google Drive, please refer to the links in the readme.
