### ISSUE TITLE
Some data files are missing. I don't know what the original data looks like.

### ISSUE THREAD

**Issue by Atomy5011** [Leot6/AMoD#2]
Hello, your project is very outstanding, which benefits me a lot as a novice.
But when I run run.py, I get a FileNotFounderError.
There is a missing path-tables-gitignore folder in the data folder, so routing_server.py reported an error.
Can you update these missing files?
Thank you very much for your contribution!

**Comment by Leot6** [comment]
Those missing data files could be generated using another repository: Manhattan-Map (https://github.com/Leot6/Manhattan-Map). Besides, I have updated them to OneDrive and Google Drive, please refer to the links in the readme.
